apiVersion: v1
kind: Service
metadata:
    name: "tgrcoolapi-service"
    namespace: tgrcoolapi
    labels:
        app: "tgrcoolapi"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "tgrcoolapi"
